### ISSUE TITLE
01_hello_world.pm6 fails to work as expected

### ISSUE THREAD

**Issue by zengargoyle** [finanalyst/GTK-Simple#1]
When the "Hello World!" button is clicked it becomes inactive and the "Goodbye!" button becomes active.  When the "Goodbye!" button is clicked.  Exploring a bit deeper it appears that `$second.clicked.tap()` code is never executed, instead the `$button.clicked.tap()` code is run whenever either button is clicked.

```
diff --git a/examples/01_hello_world.pm6 b/examples/01_hello_world.pm6
index 8e9493a..548bc54 100644
--- a/examples/01_hello_world.pm6
+++ b/examples/01_hello_world.pm6
@@ -41,7 +41,7 @@ $app.border_width = 20;
 =comment
     Using the sensitive property we can make a button unclickable.

-$second.sensitive = False;
+#$second.sensitive = False;


 =begin comment
@@ -53,13 +53,13 @@ $second.sensitive = False;
     just C<.sensitive = 0>. The C<$second> button can then be activated.
 =end comment

-$button.clicked.tap({ .sensitive = False; $second.sensitive = True });
+$button.clicked.tap({ .sensitive = False; $second.sensitive = True; say "first button tap"; });


 =comment
     Clicking the second button shall C<exit> the application's main loop.

-$second.clicked.tap({ $app.exit; });
+$second.clicked.tap({ say "second button tap"; $app.exit; });


 =comment
```

With these changes, the "Goodbye!" button is active, yet when clicked I see 'first button tap' output and "Hello World!" button disabled.

I've tried with JVM/Moar backends on Rakudo Star 2014.04 and Rakudo (not Star) 2014.05 with the same results.

I assume this example worked at some point in the past.  Sadly my Perl6 skills are not yet sufficient to dig much further.

**Comment by azawawi** [comment]
Is this still an issue with the latest?

**Comment by ghost** [comment]
Is this still a bug? I'll close this for now.
