### ISSUE TITLE
Tests not actually run by Actions

### ISSUE THREAD

**Issue by ab5tract** [finanalyst/gtk-simple#109]
The tests are essentially fudged against the Actions runner. This may be giving a false sense of security or may otherwise be detrimental.

In order to fix I believe we need to adjust  the Actions runner to include `libgtk-3-0-dev`, however that would be done.

**Comment by ab5tract** [comment]
I don't think this is actually resolvable while using the Alpine-based testrunner as there are no GTK packages in the Alpine repository. Still, maybe something to consider? Maybe not having the actions run at all would make sense, considering they are a no-op for the distribution? Or else using an Ubuntu based image or the like...

**Comment by ab5tract** [comment]
This is fixed in #110

**Comment by finanalyst** [comment]
Merged . thanks
