### ISSUE TITLE
Add notes on how to compile this and how to run the tests.

### ISSUE THREAD

**Issue by szabgab** [finanalyst/GTK-Simple#17]
I tried `prove -r -e "perl6 -Ilib" t`

and got

```
t/01_sanity.t .. 1/3 
# Failed test at t/01_sanity.t line 6
# Cannot locate native library 'libgtk-3.dylib': dlopen(libgtk-3.dylib, 1): image not found

# Failed test at t/01_sanity.t line 8
# Method 'run' not found for invocant of class 'Any'
# Looks like you failed 2 tests of 3
t/01_sanity.t .. Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/3 subtests 

Test Summary Report
-------------------
t/01_sanity.t (Wstat: 512 Tests: 3 Failed: 2)
  Failed tests:  1, 3
  Non-zero exit status: 2
Files=1, Tests=3,  9 wallclock secs ( 0.03 usr  0.00 sys +  8.77 cusr  0.25 csys =  9.05 CPU)
Result: FAIL
```

**Comment by zoffixznet** [comment]
> Cannot locate native library 'libgtk-3.dylib': dlopen(libgtk-3.dylib, 1): image not found

Do you have the GTK3 lib installed?

**Comment by szabgab** [comment]
Probably not. That's why it would be nice to have it explained in the README file :)

**Comment by zoffixznet** [comment]
Added this: https://github.com/perl6/gtk-simple/commit/3067a021a199149cbd21da642c2c39078b2daff2

If anyone can expound that (mention actual files to install on various OSs) that would be great.

**Comment by jonathanstowe** [comment]
The README needs a lot of fleshing out, TBH.  I'll take a look at this at some point today.

**Comment by azawawi** [comment]
This is fixed now in https://github.com/perl6/gtk-simple/commit/e48a477676d059069e5c6c39d74688a5c048ba26.
