### ISSUE TITLE
cannot install GTK::Simple using panda

### ISSUE THREAD

**Issue by grizzlysmit** [finanalyst/GTK-Simple#19]
panda install GTK::Simple
==> Fetching GTK::Simple
==> Building GTK::Simple
===SORRY!=== Error while compiling /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/364074153E7AD72F9C60425645AC9871DF10C969
Malformed parameter
at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/364074153E7AD72F9C60425645AC9871DF10C969:207
------>     RequestType $rt, $host, $port⏏ as Int, $path, %headers, $content?, :$s
    expecting any of:
        constraint
===SORRY!=== Error while compiling /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/364074153E7AD72F9C60425645AC9871DF10C969
Malformed parameter
at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/364074153E7AD72F9C60425645AC9871DF10C969:207
------>     RequestType $rt, $host, $port⏏ as Int, $path, %headers, $content?, :$s
    expecting any of:
        constraint

**Comment by grizzlysmit** [comment]
oh btw I'm using the 'origin/master' branch of rakudo moar rakudobrew build moar ends with 
Your branch is up-to-date with 'origin/master'

is that my problem too bleeding edge

**Comment by niner** [comment]
The bug is in LWP::Simple. I've filed a pull request for the fix.
