### ISSUE TITLE
cannot install with panda won't compile

### ISSUE THREAD

**Issue by grizzlysmit** [finanalyst/GTK-Simple#23]
panda install GTK::Simple
==> Fetching GTK::Simple
==> Building GTK::Simple
==> Testing GTK::Simple
===SORRY!=== Error while compiling /home/grizzlysmit/.panda-work/1455681681_1/Build.pm
Redeclaration of symbol Build
at /home/grizzlysmit/.panda-work/1455681681_1/Build.pm:10

**Comment by jonathanstowe** [comment]
Hi,
this was fixed (in rakudo) by https://github.com/rakudo/rakudo/commit/93e4cd697da08e5c974a0c3cb0e85563444df1b8 if you rebuild with a fresh rakudo it should be good.
