### ISSUE TITLE
Kebab the public interface

### ISSUE THREAD

**Issue by jonathanstowe** [finanalyst/GTK-Simple#29]
Parts of the public interface are using `snake_case` while I have been adding the new stuff with `kebab-case`,  obviously consistency would be better and I think that the consensus has largely converged on using `kebab-case` in new code.

Obviously this would be an in-compatible change so there would need to be a short deprecation cycle (though as it currently stands the module isn't properly versioned so this in itself is somewhat problematic,)

I'll leave this for discussion for a bit before I do anything.

**Comment by jnthn** [comment]
Consistency is the key thing, whichever way it goes. I'd be happy enough if it consistently used kebab-case; it seems to be what many things are settling on.

**Comment by finanalyst** [comment]
I've just started to work on a GTK::Simple::RadioGroup widget. 
The idea is to take a list of labels and create a group of radio buttons and MarkUpLabels. Toggle interaction would return a single integer referring to the button in the group. This is not entirely the same as a GTK RadioGroup.
I'll need some time to finish this, and send it for review. Just letting you know, I need this Widget for another project.

**Comment by jonathanstowe** [comment]
Cool.  I'm working on a couple of things but it shouldn't get in your way, I'll probably get the #28 in today which you might want to bear in mind, but it won''t stop you doing what you want to do.

**Comment by jonathanstowe** [comment]
I've done #28 now, so you may want to merge the current master before proceeding.  Hopefully the way that the property facade I have implemented works is clear enough without any further explanation, if not give me a shout.

**Comment by jonathanstowe** [comment]
To go back to the original question, there are only 10 public methods that are named in snake case - I'm minded to rename and deprecate the old names without further ado.
