### ISSUE TITLE
Successfully runned all demos on Win32, requesting official support in this module.

### ISSUE THREAD

**Issue by itsuki-hayashi** [finanalyst/GTK-Simple#3]
I just put all official builded GTK+3 dlls under the directory rakudo\bin and replaced some text in Simple.pm6 with Notepad.
'libgtk-3.so.0' -> 'libgtk-3-0.dll'
'libgobject-2.0.so' -> 'libgobject-2.0-0.dll'
One exception is 
rakudo should look for sub g_idle_add in 'libglib-2.0-0.dll' under Win32.

I hope you guys can add Win32 support to this module :) .
I am just started learning Perl 6, so my coding skill might not be enough to write patch to this module, so I wouldn't sent pull request. Just for your information.

**Comment by retupmoca** [comment]
This should be working on Windows without modification as of Dec 12, 2014
