### ISSUE TITLE
Start versioning this module

### ISSUE THREAD

**Issue by MadcapJake** [finanalyst/GTK-Simple#30]
This would let the snake-case stuff stay in a pre-1.0 version (or something else though 1.0 would follow semantic versioning)

**Comment by jonathanstowe** [comment]
Sounds reasonable, I'll put a version in if I push any changes today.

**Comment by jonathanstowe** [comment]
I'm going to arbtrarily 0.1.0 in now and it can go in straight away, and I'll version the deprecations coming out at say 0.3.0,  not keen on 1.0.0 right now as it is probably less than a fifth done if a good end-state is supporting _most_ of the widget types :)
