### ISSUE TITLE
Can't install new version at all.

### ISSUE THREAD

**Issue by finanalyst** [finanalyst/GTK-Simple#34]
I reinstalled perl6 from scratch, but still panda could not install. See below

Rakudo Star has been built and installed successfully.
Please make sure that the following directories are in PATH:
  /home/richard/perl6/rakudo-star-2016.04/install/bin
  /home/richard/perl6/rakudo-star-2016.04/install/share/perl6/site/bin

richard@ged:~/perl6/rakudo-star-2016.04$ perl6
To exit type 'exit' or '^D'

richard@ged:~/perl6/rakudo-star-2016.04$ panda install GTK::Simple
==> Fetching GTK::Simple
==> Building GTK::Simple
Found system gtk library.
==> Testing GTK::Simple
t/01-sanity.t .. ok
All tests successful.
Files=1, Tests=3, 45 wallclock secs ( 0.02 usr  0.00 sys + 42.97 cusr  1.36 csys = 44.35 CPU)
Result: PASS
==> Installing GTK::Simple
===SORRY!===
Could not find GTK::Simple::Common at line 9 in:
    /home/richard/perl6/rakudo-star-2016.04
    /home/richard/.perl6
    /home/richard/perl6/rakudo-star-2016.04/install/share/perl6/site
    /home/richard/perl6/rakudo-star-2016.04/install/share/perl6/vendor
    /home/richard/perl6/rakudo-star-2016.04/install/share/perl6
    CompUnit::Repository::AbsolutePath<79615456>
    CompUnit::Repository::NQP<70959264>
    CompUnit::Repository::Perl5<70959144>
    CompUnit::Repository::AbsolutePath<79615312>
    CompUnit::Repository::NQP<70959184>
    CompUnit::Repository::Perl5<70959224>

  in block  at sources/85367160D11E565B2D089507C79BC309215430D6 (Panda::Installer) line 61
  in sub indir at sources/24811C576EF8F85E7672B26955C802BB2FC94675 (Panda::Common) line 20
  in method install at sources/85367160D11E565B2D089507C79BC309215430D6 (Panda::Installer) line 42
  in method install at /home/richard/perl6/rakudo-star-2016.04/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 161
  in method resolve at /home/richard/perl6/rakudo-star-2016.04/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 234
  in sub MAIN at /home/richard/.bin/panda line 18
  in block <unit> at /home/richard/.bin/panda line 152

**Comment by CIAvash** [comment]
I think the new files should to be added to the `provides` section of `META6.json`.

**Comment by azawawi** [comment]
Totally Correct. It is my bad. I am working on it and testing it in my repo https://github.com/azawawi/gtk-simple/commit/ebaf0b14c6f20ec85b7ef335ce7f9453d519f3d8. 

To be safe, we should add a `panda install GTK::Simple` in `.travis.yml` after a successful `prove`. I tried also using `Test::META` but it did not report any problems.

**Comment by jonathanstowe** [comment]
Yeah, Test::META only checks that files reference in "provides" actually exist.  I figured that there may be perfect valid reasons for not wanting to install a file that may be found in "lib".
