### ISSUE TITLE
Load time

### ISSUE THREAD

**Issue by dharmatech** [finanalyst/GTK-Simple#42]
`GTK::Simple` programs take a while to start up:

```
~ $ time perl6 -e 'use GTK::Simple'

real    0m10.283s
user    0m10.000s
sys 0m0.108s
```

Any suggestions for making that faster? :-)

**Comment by azawawi** [comment]
`GTK::Simple` loads all modules under the `::Simple` namespace. Please use the following:

```
use GTK::Simple::WhatYouNeed;
```

or use [GTK::Simpler](https://github.com/azawawi/perl6-gtk-simpler)
