### ISSUE TITLE
GTK::Simple failing in Travis build

### ISSUE THREAD

**Issue by finanalyst** [finanalyst/GTK-Simple#53]
The failure seems to have started after my latest additions were committed by Jonathan, but the failure logs point to the TextView widget (I think), and do not seem to be related to my changes.

Also the failure reported on the Perl6 users list is during the Build process on Windows. I run Ubuntu, and I didn't have a problem building the latest version.

I'd like to help resolve this, but I don't actually know where to start.

**Comment by jobegrabber** [comment]
Issue was a low open file limit: https://github.com/perl6/gtk-simple/commit/f2d2599ce85afef8eac3b8afa13be91cb001b450

**Comment by jobegrabber** [comment]
Regarding failing Windows builds, the CI does not run `Build.pm` before testing - meaning necessary DLL's will not get downloaded. This is the issue I think.

**Comment by finanalyst** [comment]
I think this can be closed. Does seem to be a problem now.
