### ISSUE TITLE
Code runs fine first time, then gives warnings. 

### ISSUE THREAD

**Issue by finanalyst** [finanalyst/GTK-Simple#66]
The problem is with the ScrolledWindow code I added a couple of days ago.  At first all seems well, but ...
If I run the example (17-scrolled-window ...) from a terminal there is no error the first time. Press the exit button I have provided in the example, and the app cleans up properly. Run the example again, and there are no warnings.
HOWEVER, exit the app using the GTK window destructor (top left X on my ubuntu desktop), and the next time the app is run, warnings are generated! This should not happen. 
(See below for output).

As it happens, the warnings are about a place in the code that I was unsure about. 
gtk-scrolled-window-new() should be called with two arguments: x-hadjustment and y-hadjustment, that is two (complicated) C structs that can be used to customise the movement of the scrollbars. In the gtk documentation, the simple examples have these arguments set to NULL. So in the Raw.pm6, I use pointers, and in ScrolledWindow.pm6 I use Nil's. Since this is a 'Simple' model, I thought no need for complexity.
However, I am not sure whether I was using best practice. 
As you can see the warnings refer to these arguments.
At the same time, clean up at the end of the program should ensure that behaviour in one run of the program does not affect the behaviour of the program again. 
Hence, I am marking this as a BUG. 

Sample session:
$ perl6 ../gtk-simple/examples/17-scrolled-window-with-textview.p6 
==== comment. No output on stdout or stderr. The app was ended using the Exit button
$ perl6 ../gtk-simple/examples/17-scrolled-window-with-textview.p6 
==== comment. ditto
$ perl6 ../gtk-simple/examples/17-scrolled-window-with-textview.p6 
==== comment. This time, I exited the app by destroying the window, not exiting the app.
$ perl6 ../gtk-simple/examples/17-scrolled-window-with-textview.p6 
(17-scrolled-window-with-textview.p6:8210): Gtk-CRITICAL *_: gtk_scrolled_window_new: assertion 'GTK_IS_ADJUSTMENT (hadjustment)' failed
(17-scrolled-window-with-textview.p6:8210): Gtk-CRITICAL *_: gtk_scrolled_window_set_policy: assertion 'GTK_IS_SCROLLED_WINDOW (scrolled_window)' failed
(17-scrolled-window-with-textview.p6:8210): Gtk-CRITICAL *_: gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed
(17-scrolled-window-with-textview.p6:8210): Gtk-CRITICAL *_: gtk_box_pack: assertion 'GTK_IS_WIDGET (child)' failed
(17-scrolled-window-with-textview.p6:8210): Gtk-CRITICAL **: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by finanalyst** [comment]
Update:
I was using Rakudo.star 16.04 until today. I have just updated to 16.07.
Now I am getting segmentation faults or the ScrolledWindow is not working.
Sigh!
Any help on this? I have a feeling this may be a common problem when upgrading Rakudo and not altogether related to GTK::Simple

**Comment by timo** [comment]
One thing i can say is that if you run any gtk-based app in a terminal, you'll see between twenty and two million "Gtk-CRITICAL" outputs. i can only infer from that that these critical messages are 100% harmless …

I'll have a look around the 'net and the code anyway

**Comment by timo** [comment]
Ah, yes. By declaring the signature of the native function to be (), you're telling MoarVM that gtk_scrolled_window_new won't be looking for any arguments at all. That means MoarVM will not write any particular values into the registers (or onto the stack, depending on the calling convention; registers in this case) that the function will interpret as its first and second arguments.

This causes the value the function receives for its first two arguments to be essentially random values. They are very, very unlikely to happen to be valid pointers.

The reason why you can't just leave the signature empty and have it Do The Right Thing is that NativeCall doesn't have access to the heade file that would tell it that there _are_ arguments the target function will be looking at.

I'm patching the code as I type this :)

**Comment by finanalyst** [comment]
Timo,Thanks for feedback.Although I read a hint about Null in NativeCall documentation, I think it should be more explicit. 
In the case we are discussing here, the C oriented documentation used Null in the examples. You used Pointer. I think this should be documented better.
I'm currently without internet (moving flat) otherwise I might attempt this myself.
RegardsRichard
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: timo notifications@github.com Date: 12/09/2016  03:22  (GMT+08:00) To: perl6/gtk-simple gtk-simple@noreply.github.com Cc: Richard Hainsworth rnhainsworth@gmail.com, Author author@noreply.github.com Subject: Re: [perl6/gtk-simple] Code runs fine first time, then gives warnings. (#66) 
Ah, yes. By declaring the signature of the native function to be (), you're telling MoarVM that gtk_scrolled_window_new won't be looking for any arguments at all. That means MoarVM will not write any particular values into the registers (or onto the stack, depending on the calling convention; registers in this case) that the function will interpret as its first and second arguments.

This causes the value the function receives for its first two arguments to be essentially random values. They are very, very unlikely to happen to be valid pointers.

The reason why you can't just leave the signature empty and have it Do The Right Thing is that NativeCall doesn't have access to the heade file that would tell it that there are arguments the target function will be looking at.

I'm patching the code as I type this :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/perl6/gtk-simple","title":"perl6/gtk-simple","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/perl6/gtk-simple"}},"updates":{"snippets":[{"icon":"PERSON","message":"@timo in #66: Ah, yes. By declaring the signature of the native function to be (), you're telling MoarVM that gtk_scrolled_window_new won't be looking for any arguments at all. That means MoarVM will not write any particular values into the registers (or onto the stack, depending on the calling convention; registers in this case) that the function will interpret as its first and second arguments.\r\n\r\nThis causes the value the function receives for its first two arguments to be essentially random values. They are very, very unlikely to happen to be valid pointers.\r\n\r\nThe reason why you can't just leave the signature empty and have it Do The Right Thing is that NativeCall doesn't have access to the heade file that would tell it that there _are_ arguments the target function will be looking at.\r\n\r\nI'm patching the code as I type this :)"}],"action":{"name":"View Issue","url":"https://github.com/perl6/gtk-simple/issues/66#issuecomment-246198765"}}}
