### ISSUE TITLE
Finding ENUM values eg. GTK_ORIENTATION_HORIZONTAL for PANED

### ISSUE THREAD

**Issue by finanalyst** [finanalyst/GTK-Simple#68]
I am having trouble adding a 'Pane' widget.
I have added all the functions referred to the GTK3 manual page to raw. However, when I run a minimal app, I get a blank window. (The current code of example 18 in my repo is minimal. As you will see I have commented out all of the extra code to show different code). Also, I have simplified the BUILD submethod in Raw.pm6 to try to identify the problem.
GTK gives the initialisation routine as gtk_paned_new( orientation ). 'orientation' is an enumeration with two elements, GTK_ORIENTATION_HORIZONTAL and GTK_ORIENTATION_VERTICAL
I assumed the actual values are 0 and 1, but I can't actually find the .h file that defines them in the gtk sources.
The code is in finanalyst/gtk-simple. I have not done a push request because the example file is not running correctly yet.
I'm willing to keep working at this, but I have run out of ideas as to how to get this to work. I have Googled GTK Paned, but there does not seem to be any link about a problem or any special code needed.

**Comment by jonathanstowe** [comment]
On this computer they are defined in `/usr/include/gtk-3.0/gtk/gtkenums.h`

**Comment by finanalyst** [comment]
GTK_ORIENTATION_HORIZONTAL = 0
But Paned still does not work.
Not sure what to do next.

**Comment by finanalyst** [comment]
Closing this issue for now.
