### ISSUE TITLE
Trying to use Cairo in DrawingArea

### ISSUE THREAD

**Issue by finanalyst** [finanalyst/GTK-Simple#69]
The Cairo documentation is sparse and there is no example for the use of DrawingArea.

Also the following error is puzzling:
 $perl6 test_lib.p6 
Could not find symbol '&ConnectionHandler'
  in method add-draw-handler at /home/richard/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/A6D434FC7BEE2A422FB2B8F6CF413E78905D1848 (GTK::Simple::DrawingArea) line 33
  in block <unit> at test_lib.p6 line 20
Actually thrown at:
  in method add-draw-handler at /home/richard/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/A6D434FC7BEE2A422FB2B8F6CF413E78905D1848 (GTK::Simple::DrawingArea) line 33
  in block <unit> at test_lib.p6 line 20

$ cat test_lib.p6
#!/usr/bin/env perl6 
use v6.c;
use GTK::Simple;
use Cairo;
use GTK::Simple::DrawingArea;

my $app = GTK::Simple::App.new(:title<TestingCairo>);
my $da = GTK::Simple::DrawingArea.new;
gtk_simple_use_cairo;

$app.set-content( $da );
$app.border-width = 20;
$da.size-request(300,300);
my $ctx = $da.add-draw-handler( &rect-do );
$app.run;

sub rect-do( $d, $ctx ) {
    given $ctx {
        .rgb(0, 0.7, 0.9);
        .rectangle(10, 10, 50, 50);
        .fill :preserve; .rgb(1, 1, 1);
        .stroke
    };
}

**Comment by jonathanstowe** [comment]
The `GTK::Simple::DrawingArea.add-draw-handler` references some type that isn't defined. I'll take a look later.

**Comment by jonathanstowe** [comment]
That may fix that problem but there may be another issue

**Comment by dwarring** [comment]
@finanalyst 
Please try again with latest Gtk::Simple, and Cairo, and with slightly amended code sample as below
```
use v6.c;
use GTK::Simple;
use GTK::Simple::DrawingArea;

my $app = GTK::Simple::App.new(:title<Test>);
my $da = GTK::Simple::DrawingArea.new;
gtk_simple_use_cairo;

$app.set-content( $da );
$app.border-width = 20;
$da.size-request(300,300);

sub rect-do( $d, $ctx ) {
    given $ctx {
	.rgb(0, 0.7, 0.9);
	.rectangle(10, 10, 50, 50);
	.fill :preserve; .rgb(1, 1, 1);
	.stroke
    };
}

my $ctx = $da.add-draw-handler( &rect-do );
$app.run;
```

**Comment by dwarring** [comment]
I've also added this as examples/18-cairo-draw-handler.pl6 e42501e

**Comment by dwarring** [comment]
Please reopen, if there's any further problems.
