### ISSUE TITLE
GTK::Simple::App not exported by default or explicitly imported in examples

### ISSUE THREAD

**Issue by Digicrat** [finanalyst/GTK-Simple#73]
Most of the examples (both in the examples directory, and the quick start example in the readme docs) fail to run with the latest rakudobrew installation with the error "GTK::Simple::App is not declared."  Adding a "use GTK::Simple::App" in the script resolves the error.  This is true for examples 01-08 and 17.

On a related note of examples failing:

- Example 05 fails with "Cannot locate symbol 'gtk_action_bar_new' in native library 'libgtk-3.so".
- 07 seemingly works, but gives an error "Cannot locate symbol gtk_text_view_set_monospace"
- 13 fails with "Cannot locate symbol gtk_places_sidebar_get_show_trash"

**Comment by jonathanstowe** [comment]
Looks like fallout from the "lexical use" change, I'll take a look later.

**Comment by jonathanstowe** [comment]
I suspect that the other problems that you are seeing are related to the version of GTK that you have as I can't reproduce here.
