### ISSUE TITLE
Add a "gui" tag to the meta-6 file

### ISSUE THREAD

**Issue by trosel** [finanalyst/GTK-Simple#75]
Add `"tags" : ["gui"],`

**Comment by jonathanstowe** [comment]
Any reason you can't make a PR for this?

**Comment by trosel** [comment]
I didn't know if a special process had to be done to update the ecosystem with the tag. Or if it somehow automatically updated changes to modules.perl6.org

#76

**Comment by Altai-man** [comment]
https://github.com/perl6/gtk-simple/pull/76 was merged, so closed.
