### ISSUE TITLE
RFE: Please add Progress Bar to the list of examples

### ISSUE THREAD

**Issue by ToddAndMargo** [finanalyst/GTK-Simple#77]
https://github.com/perl6/gtk-simple/blob/master/lib/GTK/Simple/ProgressBar.pm6

**Comment by faraco** [comment]
@ToddAndMargo

Hi.

 I'm not sure what do you mean by *list of examples*? Where is this list you are referring to?

**Comment by ToddAndMargo** [comment]
On 08/31/2018 10:10 PM, Cocoa Paw wrote:
> @ToddAndMargo <https://github.com/ToddAndMargo>
> 
> Hi.
> 
> I'm not sure what do you mean by /list of examples/? Where is this list 
> you are referring to?

https://github.com/perl6/gtk-simple/tree/master/examples

**Comment by ghost** [comment]
@ToddAndMargo I made a basic ProgressBar example and pushed at this commit https://github.com/perl6/gtk-simple/commit/4dadc9080bcd0e03e695f720c1fe5dec67a175d8

**Comment by ToddAndMargo** [comment]
On 08/31/2018 11:44 PM, Cocoa Paw wrote:
> @ToddAndMargo <https://github.com/ToddAndMargo> I made a basic 
> ProgressBar example and pushed at this commit 4dadc90 
> <https://github.com/perl6/gtk-simple/commit/4dadc9080bcd0e03e695f720c1fe5dec67a175d8>

Thank you!

**Comment by ghost** [comment]
@ToddAndMargo I'll close this issue for now.
