### ISSUE TITLE
GObject Introspection?

### ISSUE THREAD

**Issue by MattOates** [finanalyst/GTK-Simple#80]
I was wondering if anyone who's worked on this module has much knowledge of GIR/[GObject Introspection](https://wiki.gnome.org/Projects/GObjectIntrospection) and how easy/hard it might be to wire it up to NativeCall in a similar way to [GPTrixie](https://github.com/Skarsnik/gptrixie)?

I'm mostly asking because [Apache Arrow](https://arrow.apache.org/) is also another project using GObject to define all of the low level memory map of its data structures. I was thinking about making a DataFrame type library for Perl 6 to go in the Stats module, and noticed there is a bit of a push towards dealing with a unified memory model for interop. Could bind the C implementation directly but there is a short cut via GObject Introspection that the Ruby binding uses that might be worth doing instead. Especially if its also useful for creating a more complete GTK+ binding at the same time?

Does anyone have any input on the feasibility of this? Or know anything about GIR/GObject Introspection already?

**Comment by finanalyst** [comment]
No answers for four years here and the question is not really GTK::Simple specific, so closing

**Comment by Xliff** [comment]
@finanalyst - Wish I hadn't missed this message, so I hope you get the notification:

You might want to look at my [p6-GIR](https://github.com/Xliff/p6-GIR.git) module. In the meantime I will take a look at Apache Arrow and see if I can nom it into another project in my p6-GLib line.
