### ISSUE TITLE
rfe: example with a scroll bar

### ISSUE THREAD

**Issue by ToddAndMargo** [finanalyst/GTK-Simple#84]
Request for Enhancement:

Over on https://github.com/perl6/gtk-simple/tree/master/examples, would you please consider adding an example of a dismissable text box to include text dynamically added with vertical and horizontal scroll bars as the text grows/gets bigger than the window?

Many thanks,
-T

**Comment by ghost** [comment]
Anyone is working on this?

**Comment by Xliff** [comment]
@ToddAndMargo: Are you expecting that TextView to be opened in a new window or a dialog?

**Comment by finanalyst** [comment]
There are examples with Scroll bars now in the examples directory. This issue seems to be resolved now; can be reopened if not.
