### ISSUE TITLE
how install Cairo

### ISSUE THREAD

**Issue by alainbebe** [finanalyst/GTK-Simple#86]
Hi,

I don't understand how install Cairo on Debian Stretch.
I do
apt install libcairo2-dev (and i ha ve libcairo2-dev is already the newest version )
but I have always 'Cairo' module is not installed - can't run example

Have an idea ?

**Comment by Xliff** [comment]
@alainbebe : You need the Cairo perl module. You should be able to install this via the following command:

```
zef install Cairo
```

**Comment by alainbebe** [comment]
Thank,
Stupidly, i try "zef install cairo", may be add the good instruction to "The Cairo module needs to be installed, for this example to work"

**Comment by ghost** [comment]
> Thank,
> Stupidly, i try "zef install cairo", may be add the good instruction to "The Cairo module needs to be installed, for this example to work"

Done at da2dbb3c20614c4536b1601e08d060f681ff6ce4. Thanks for the suggestion. :)
