### ISSUE TITLE
TextView / Scroll Example doesn't work

### ISSUE THREAD

**Issue by Scimon** [finanalyst/GTK-Simple#87]
The TextView in an ScrolledWindow exmaple fails. It would appear that TestViews can't be editted within the code giving an error of "Cannot modify an immutable Str ()"

**Comment by jonathanstowe** [comment]
I think you're going to have to talk us through this as I can't get the as-is ```examples/17-scrolled-window-with-textview.p6``` to do anything untoward.

**Comment by Scimon** [comment]
Sorry, was mostly working through my Advent calender article at the time (suprise guess what it's about?).
I'll investigate further.

**Comment by Xliff** [comment]
This is due to the fact that the accessor method:

```perl6
method text() {
    Proxy.new:
        FETCH => {
            gtk_text_buffer_get_text($!buffer, self!start-iter(),
                self!end-iter(), 1)
        },
        STORE => -> \c, \text {
            gtk_text_buffer_set_text($!buffer, text.Str, -1);
        }
}
```

Is not "is rw". I think this code worked up until a recent commit of Perl6, where the bug that allowed this to work without the 'rw' trait was fixed.

**Comment by jonathanstowe** [comment]
Yeah that's entirely what it is.

Let me have a quick look at that.

**Comment by jonathanstowe** [comment]
As it stands the constructor for the TextView doesn't  do anything with a ```text``` argument.  Arguably it should but that should probably be handled separately as it will require a bit of a rework of the whole class.
