### ISSUE TITLE
Host used for downloading windows DLLs is down

### ISSUE THREAD

**Issue by khalidelboray** [finanalyst/GTK-Simple#88]
In [this](https://github.com/perl6/gtk-simple/blob/master/Build.pm#L97) the `http://gtk-dlls.p6c.org` domain is down

**Comment by JJ** [comment]
Thanks for the warning. All p6c are down. Don't know where those DLLs might be now...

**Comment by khalidelboray** [comment]
i found this [Bundle](http://www.tarnyko.net/dl/gtk.htm) maybe what in `\bin` works otherwise i will try to compile it
