### ISSUE TITLE
Trying to read the `.text` property of a TextView results in an abort.

### ISSUE THREAD

**Issue by ramillies** [finanalyst/GTK-Simple#89]
Here is a minimal example to show the bug off:

    use GTK::Simple::App;
    use GTK::Simple::TextView;
    
    my $app       = GTK::Simple::App.new(:title("Crash in 2 seconds."));
    my $text-view = GTK::Simple::TextView.new;
    
    $text-view.text = "acfd";
    
    start { sleep 2; say $text-view.text; }
    
    $app.set-content($text-view);
    $app.show;
    $app.run;

When this is ran, it correctly shows a window with a TextView containing "acdf". However, after 2 sec, instead of "acdf" (or whatever the TextView contents are at that moment) being printed into the terminal, the program crashes:

    $ crash.p6
    malloc(): invalid size (unsorted)
    [1]    8571 abort      crash.p6

This bug also affects the example 11 (`examples/11-file-chooser-button.pl6`) that crashes when the file is chosen from the dialog.

------
The operating system is Debian bullseye/sid, Perl 6 version 2019.07.1, GTK::Simple version 0.1.11, and libgtk3 version 3.24.10-1 (coming from Debian repositories).

Of course I will be happy to provide more information as needed; I'm just not really sure what to look for. If you would like me to use some gdb on it, or get some core dumps, valgrind logs or anything like that, just ask.

Thanks!

**Comment by jnthn** [comment]
> start { sleep 2; say $text-view.text; }

This won't go well. In just about all UI frameworks, you can only access the UI from the designated UI thread; trying to do otherwise will go very badly. You can use `Gtk::Simple::Scheduler` to marshall the operation onto the UI thread.

**Comment by ramillies** [comment]
I'm sorry, I didn't know that. However, the bug has nothing to do with it. If I bind it to a button click, the crash still occurs:

    use GTK::Simple::App;
    use GTK::Simple::TextView;
    use GTK::Simple::Button;
    use GTK::Simple::VBox;
    
    my $app       = GTK::Simple::App.new(:title("Crash"));
    my $text-view = GTK::Simple::TextView.new;
    
    $text-view.text = "acfd";
    
    $app.set-content(GTK::Simple::VBox.new(my $b = GTK::Simple::Button.new(label => "Crash Now!"), $text-view));
    
    $b.clicked.tap({ say $text-view.text; });
    
    $app.show;
    $app.run;

**Comment by jnthn** [comment]
OK, then that looks like a real problem with `GTK::Simple`.

**Comment by ghost** [comment]
Hi @ramillies.

I tried both of your examples and I can't reproduce the bug. They both works fine and doesn't crash for me.

Do you mind to give us some details about your perl6 implementation such as version and which platform you are using GTK::Simple on?

Thanks.

**Comment by ramillies** [comment]
Hi,
the most basic details are in the original post:

> The operating system is Debian bullseye/sid, Perl 6 version 2019.07.1, GTK::Simple version 0.1.11, and libgtk3 version 3.24.10-1 (coming from Debian repositories).

Would that be sufficient? I can provide more if you like.

**Comment by ghost** [comment]
@ramillies Whoops! My bad!!!

**Comment by jonathanstowe** [comment]
I can confirm that the original code still fails, BT is:

```
#0  0x00007ffff7578625 in raise () at /lib64/libc.so.6
#1  0x00007ffff75618d9 in abort () at /lib64/libc.so.6
#2  0x00007ffff75bc4af in __libc_message () at /lib64/libc.so.6
#3  0x00007ffff75c3a9c in annobin_top_check.start () at /lib64/libc.so.6
#4  0x00007ffff75c6a14 in _int_malloc () at /lib64/libc.so.6
#5  0x00007ffff75c8309 in malloc () at /lib64/libc.so.6
#6  0x00007ffff7991c82 in push () at //usr/local/lib/libmoar.so
#7  0x00007ffff79e6216 in resolve_using_guards () at //usr/local/lib/libmoar.so
#8  0x00007ffff79e6f64 in MVM_spesh_plugin_resolve () at //usr/local/lib/libmoar.so
#9  0x00007ffff79425be in MVM_interp_run () at //usr/local/lib/libmoar.so
#10 0x00007ffff7957b6a in start_thread () at //usr/local/lib/libmoar.so
#11 0x00007ffff73dd4e2 in start_thread () at /lib64/libpthread.so.0
#12 0x00007ffff763d693 in clone () at /lib64/libc.so.6
```

**Comment by jonathanstowe** [comment]
It looks like the buffer for the GtkTextIter for the end iterator when fetching the text was too small.

Works for me now, if you'd like to try again.

**Comment by finanalyst** [comment]
This issue seems to have been resolved, so closing
