### ISSUE TITLE
use just Github Actions for CI

### ISSUE THREAD

**Issue by ghost** [finanalyst/GTK-Simple#95]
since Github Actions now available to all open source projects, and highly integrated with Github, also offers Windows and self hosted build as options...I think we can start replacing appveyor and travis ci with github actions CI instead of using two

**Comment by finanalyst** [comment]
Please could you help me with this. I'd really like to do this, but some practical set up scripts, or config files, would be useful.

**Comment by finanalyst** [comment]
Done
