### ISSUE TITLE
RFE: 07-text.pl6: show returned text

### ISSUE THREAD

**Issue by ToddAndMargo** [finanalyst/GTK-Simple#97]
https://github.com/raku-community-modules/gtk-simple/blob/master/examples/07-text.pl6

Request for Enhancement (RFE):

Would you please consider showing (say) the returned text in the above example?

Many thanks,
-T

**Comment by JJ** [comment]
It's a simple modification. We'd happily accept pull requests with this.

**Comment by finanalyst** [comment]
Not sure what this issue is about. The example creates a GTK box that shows the text in the box.
Is this a Windows installation issue?

**Comment by finanalyst** [comment]
Closing issue as its unclear what it wanted. If there is clarification, it can be reopened
