### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JJ** [finanalyst/GTK-Simple#98]
'Nuff said. There's none. We need some.

**Comment by finanalyst** [comment]
Where do you want documentation? A bigger README.md? 

There are lots of examples that are fairly well commented.

**Comment by JJ** [comment]
Per-method documentation, for instance. A walk-through tutorial. A reference of methods and data structures.

**Comment by ghost** [comment]
@jj We certainly need the reference.

**Comment by finanalyst** [comment]
Where would the Tutorial be located?
Problem with all Modules is that once the module is installed by zef, its not clear how to get at accompanying Pod or documentation files.
The only way I have found is to look at the examples on the module's repo. The examples have a lot of comments.

**Comment by JJ** [comment]
In a .rakumod file, preferably, I guess.

**Comment by finanalyst** [comment]
.rakumod or .rakupod ??
Is this a conversation I have missed?

**Comment by finanalyst** [comment]
Added links to first four examples, which are each mini tutorials.
